name: Code Quality checks

on:
  pull_request:
  push:
    branches: [main]

jobs:
  code-quality:
    name: Run linter and prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm ci

      - name: ES syntax linter
        run: npm run lint -- --fix

      - name: Prettier
        run: npm run prettier -- --write

      - name: Commit formatted code
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -a -m "Auto-format code"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
